name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - name: Check-out repository
        uses: actions/checkout@v2

      # Initialize test dependencies and run all BATS tests
      - name: Run Tests
        run: make test
